[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
program_0_anchor_basics = "2vBz5hPhDTrH3YqQ69RvU74vMyeynvJTvocZVCpp6LxY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
